### ISSUE TITLE
Standardization of discharge curve

### ISSUE THREAD

**Issue by Heyuong** [petermattia/revisit-severson-et-al#5]
Hello, in the cycle process, how to handle the capacity-voltage curve standardization of all discharge curves of 4C, and what are the steps of smooth spline function fitting? Thank you very much.

**Comment by petermattia** [comment]
See here for the original MATLAB code for this step.
https://github.com/chueh-ermon/BMS-autoanalysis/blob/master/VQlinspace.m

**Comment by petermattia** [comment]
Closing for now.
